apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astaire
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: astaire
    spec:
      containers:
      - image: "{{REPO}}/clearwater/astaire:latest"
        name: astaire
        ports:
        - containerPort: 22
        - containerPort: 11211
        - containerPort: 11311
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 11311
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 11311
        volumeMounts:
        - name: astairelogs
          mountPath: /var/log/astaire
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/astaire/astaire_current.txt" ]
        volumeMounts:
        - name: astairelogs
          mountPath: /var/log/astaire
      volumes:
      - name: astairelogs
        emptyDir: {}
      restartPolicy: Always
