apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: chronos
  name: chronos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: chronos
    spec:
      containers:
      - image: "{{REPO}}/clearwater/chronos:latest"
        name: chronos
        ports:
        - containerPort: 22
        - containerPort: 7253
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 7253
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 7253
        volumeMounts:
        - name: chronoslogs
          mountPath: /var/log/chronos
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/chronos/chronos_current.txt" ]
        volumeMounts:
        - name: chronoslogs
          mountPath: /var/log/chronos
      volumes:
      - name: chronoslogs
        emptyDir: {}
      restartPolicy: Always
